# frozen_string_literal: true

$LOAD_PATH << '../lib'
require 'fileutils'
require 'guard/git'

ignore(%r{^output/.*})

Guard::Git.enable!

guard :rubocop, cli: ['--auto-correct'] do
  watch(/.+\.rb$/)
end

guard :shell do
  watch('input/is_guard_running') { FileUtils.touch 'output/guard_is_running' }
  watch(/.*/) { FileUtils.touch 'output/guard_ran' }
end
